"""changes

Revision ID: 17ac7fe7bf18
Revises: c0f738419853
Create Date: 2025-04-22 00:48:20.066998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17ac7fe7bf18'
down_revision = 'c0f738419853'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connection_request', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_connection_request', ['requester_id', 'receiver_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connection_request', schema=None) as batch_op:
        batch_op.drop_constraint('unique_connection_request', type_='unique')

    # ### end Alembic commands ###
