"""TESTING CONNECTION FEATURE

Revision ID: 18067aad7a03
Revises: 17ac7fe7bf18
Create Date: 2025-04-22 21:40:17.714015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18067aad7a03'
down_revision = '17ac7fe7bf18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('connection_request', schema=None) as batch_op:
        batch_op.alter_column('requester_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('receiver_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.drop_constraint('unique_connection_request', type_='unique')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['receiver_id'], ['propel_user_id'])
        batch_op.create_foreign_key(None, 'user', ['requester_id'], ['propel_user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connection_request', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['requester_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['receiver_id'], ['id'])
        batch_op.create_unique_constraint('unique_connection_request', ['requester_id', 'receiver_id'])
        batch_op.alter_column('receiver_id',
               existing_type=sa.String(length=255),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('requester_id',
               existing_type=sa.String(length=255),
               type_=sa.INTEGER(),
               existing_nullable=False)

    op.drop_table('page')
    # ### end Alembic commands ###
