"""Add NoteReport model

Revision ID: 68957169812d
Revises: 2b90828e49d4
Create Date: 2025-04-11 10:53:54.620441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68957169812d'
down_revision = '2b90828e49d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('reporter_user_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['note_id'], ['note.id'], ),
    sa.ForeignKeyConstraint(['reporter_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('contributions',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('contributions',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)

    op.drop_table('note_report')
    # ### end Alembic commands ###
